### ISSUE TITLE
Hope the side bar can scroll

### ISSUE THREAD

**Issue by zeteticl** [ernieayala/ernies-modern-layout#133]
![image](https://user-images.githubusercontent.com/23254376/127748373-da1536e1-6aad-437e-a604-7567ec9f4bcc.png)

When more module is installed, there will be more boxes on the left
sometime it couldt show the box  or cover the playerlist
So  i hope that can scroll or collapse side bar

**Comment by ernieayala** [comment]
I think the best solution for this now is for you to use the Controls Align to Top option.
![controls](https://user-images.githubusercontent.com/9342233/131225323-08bd707b-82b7-4063-8a8e-7be957d766a6.JPG)

Because of the markup structure - I won't be able to add any sort of scroll bar on the first layer of controls.
