### ISSUE TITLE
Compatibility with Automated Animated menu

### ISSUE THREAD

**Issue by Iankid** [ernieayala/ernies-modern-layout#151]
Compatibility with Automated Animated menu
![ErnieAA](https://user-images.githubusercontent.com/60759323/152585899-9453b2ef-63e4-4e44-83bb-9df0552c5832.png)

**Comment by ernieayala** [comment]
Think this is an issue conflicting with other mods. When I have SFRPG and my mod installed it looks mostly usable. Might have been fixed since posting this or might be conflict with another css mod. 
![sfrpg-auto-ani](https://user-images.githubusercontent.com/9342233/179326520-1c6e4cf9-eb18-4676-a963-75a26bf108b5.JPG)
