### ISSUE TITLE
PF2e Unable to change important UI BG color

### ISSUE THREAD

**Issue by IanYuy** [ernieayala/ernies-modern-layout#200]
In PF2e, none of the options allow you to change the background color of the right-click menu. This becomes an issue because it requires that no matter what color theme you pick, you must use a very light color text to offset that dark blue.
![q2nREHO](https://user-images.githubusercontent.com/29584099/214059272-024cb610-9b3c-4b51-a4bb-755e99707149.png)

However, other modules add elements that can't be changed and inherently conflict with leaving a default light colored text. Like Player Overview, which puts white bands regardless of the other colors.
![L2KT2xd](https://user-images.githubusercontent.com/29584099/214059451-0048147a-71ce-4cf4-b143-9760dfd9066c.png)

Or, PF2e Modifiers Matter, which adds a gm-bg color in the text box.
![hBgtlEe](https://user-images.githubusercontent.com/29584099/214059564-494b548b-c287-40d9-bc16-341a597ec266.png)

This makes picking a text color that allows all of these to be readable impossible. Being able to change the background of the right-click menu seems like the best solution.

**Comment by ernieayala** [comment]
All three of these are module conflicts. You can submit individual tickets for each module for me to investigate in the future.

**Comment by rjbprime** [comment]
I seem to be getting the top image error with DnD5e as well. Not sure which module out of about 150 is causing it. @IanYuy: Can you send a copy of your mod list when this issue was occurring, and I'll compare with my list, then I could help narrow it down.

EDIT: I managed to find my culprit for the Dark Text on Dark Background (Image 1 in your post @IanYuy). I'll see if there is a ticjt for it now.
